stages:
  - validate

default:
  image: node:20
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/

validate:
  stage: validate
  script:
    - npm ci
    - npm run lint
    - npm run test
    - npm run build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'
